version: '3'
services:
  workspace-${FLAVOR}-prebuilt:
    env_file: ../configs/.env
    image: ${ACRLOGINSERVER}/${PREFIX}-${FLAVOR}:${TAG}
    volumes:
      - "..:/workspace"
      - "../configs/.databrickscfg:/home/userddc/.databrickscfg"
      - "../configs/.jupyter:/home/userddc/.jupyter"
      - "~/.gitignore:/home/userddc/.gitignore"
      - "~/.ssh:/home/userddc/.ssh"
    ports:
      - "127.0.0.1:8888:8888"
    command: sleep infinity