version: '3'
services:
  workspace-${FLAVOR}:
    env_file: ../configs/.env
    build:
      context: .
      dockerfile: Dockerfile-${FLAVOR}
    volumes:
      - "..:/workspace"
      - "../configs/.databrickscfg:/home/userddc/.databrickscfg"
      - "../configs/.jupyter:/home/userddc/.jupyter"
      - "~/.gitignore:/home/userddc/.gitignore"
      - "~/.ssh:/home/userddc/.ssh"
    ports:
      - "127.0.0.1:8888:8888"
    command: sleep infinity